# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hf-puller',
                'doc_host': 'https://xianbaoqian.github.io',
                'git_url': 'https://github.com/xianbaoqian/hf-puller',
                'lib_path': 'hf_puller'},
  'syms': {'hf_puller.core': {'hf_puller.core.foo': ('core.html#foo', 'hf_puller/core.py')}}}
